trigger: none
resources:
  repositories: 
  - repository: ExternalTemplates
    type: git
    name: DEVOPS/AZURE-DEVOPS-TEMPLATES
    ref: 'refs/heads/master'
schedules: 
- cron: "0 0 * * *" 
  displayName: Daily midnight build
  branches:
    include:
    - refs/heads/develop
  always: false

variables:
- group: SITESWEB.PIPELINES

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    pool:
      name: $(BuildPoolName)
    steps:      
      - template: 'yaml-templates/steps/BuildSonarManualScan.yml@ExternalTemplates'
        parameters:
            sonarQube: 'SONAR CR-TI-SITESWEB-DATABASE'
            cliProjectKey: 'SITESWEB-DATABASE'