CREATE   FUNCTION [dbo].[FN_VALIDACION_CONTRAINT_REACTIVAR_tblCedis_C4](@REACTIVAR BIT, @Fk_Id_Pais INT)
RETURNS BIT
AS
BEGIN
	--
	-- VALIDA SI EL PAIS ESTA ACTIVO PARA REACTIVAR UNA CEDIS
	DECLARE @RESULT BIT = 1
	--
	IF @REACTIVAR = 1 BEGIN
		--
		SET @RESULT = (SELECT Activo FROM tblPais WHERE Id = @Fk_Id_Pais)
		--
	END
	--
    RETURN(@RESULT)
	--
END