CREATE   FUNCTION [dbo].[FN_VALIDACION_CONTRAINT_tblCedis_C4](@Fk_Id_Pais INT)
RETURNS BIT
AS
BEGIN
	--VALIDA SI EL PAIS ESTA ACTIVO
	RETURN (SELECT Activo FROM tblPais WHERE Id = @Fk_Id_Pais)
	--
END