CREATE   FUNCTION FN_VALIDACION_CONTRAINT_T2_C4(@REACTIVAR BIT, @FK_ID_DEPARTAMENTO INT)
RETURNS BIT
AS
BEGIN
	--
	-- askdfljalksdjflkajsd
	DECLARE @RESULT BIT = 1
	--
	IF @REACTIVAR = 1 BEGIN
		--
		SET @RESULT = (SELECT Activo FROM tblDepartamento WHERE Id = @FK_ID_DEPARTAMENTO)
		--
	END
	--
    RETURN(@RESULT)
	--
END